# Generated by Django 4.2.4 on 2023-09-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('categoria_empresa', models.CharField(max_length=100)),
                ('quitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
        ),
    ]
